/**
 * Theme catalog for built-in role-name/persona mappings with bilingual support.
 */

import type { PersonaThemeKey, RoleThemeMapping } from '../types.js'

export const THEME_CATALOG: Record<PersonaThemeKey, Record<string, RoleThemeMapping>> = {
  modern: {
    commander: {
      roleKey: 'commander',
      name: '阿尔法总指挥官',
      nameEn: 'Alpha Commander',
      avatar: '🎖️',
      color: '#ef4444',
      title: '全盘统筹·决策审核',
      titleEn: 'Orchestration & Gatekeeping',
      catchphrase: '把控全局方向，严格质量把关，决断分工！',
      catchphraseEn: 'Control the direction, enforce the bar, and drive decisive ownership!',
    },
    researcher: {
      roleKey: 'researcher',
      name: '深潜情报调研员',
      nameEn: 'Deep-dive Researcher',
      avatar: '🔍',
      color: '#06b6d4',
      title: '全网搜索·竞品深潜',
      titleEn: 'Web Search & Competitive Intelligence',
      catchphrase: '穷尽外部信源，以事实和数据为团队开路。',
      catchphraseEn: 'Exhaust all external sources, leading the team with facts and data.',
    },
    backend: {
      roleKey: 'backend',
      name: '核心后端架构师',
      nameEn: 'Core Backend Architect',
      avatar: '💻',
      color: '#3b82f6',
      title: '逻辑建模·高并发高可用',
      titleEn: 'Data Modeling & Scalable Architecture',
      catchphrase: '逻辑严密，高内聚低耦合，坚固如磐石。',
      catchphraseEn: 'Rigorous logic, high cohesion, loose coupling, solid as bedrock.',
    },
    frontend: {
      roleKey: 'frontend',
      name: '交互体验设计师',
      nameEn: 'Interaction & UI Designer',
      avatar: '🎨',
      color: '#ec4899',
      title: '界面美学·无障碍交互',
      titleEn: 'Interface Aesthetics & Accessible Flow',
      catchphrase: '让复杂的技术通过优雅的界面自然流淌。',
      catchphraseEn: 'Let complex power flow naturally through elegant design.',
    },
    qa: {
      roleKey: 'qa',
      name: '红队质量审计官',
      nameEn: 'Red Team QA Auditor',
      avatar: '🛡️',
      color: '#f59e0b',
      title: '极限压测·漏洞挖掘',
      titleEn: 'Adversarial Testing & Edge Cases',
      catchphrase: '用最严苛的眼光审视每一处隐患。',
      catchphraseEn: 'Scrutinize every blind spot with the strictest eye.',
    },
    writer: {
      roleKey: 'writer',
      name: '首席文案记录官',
      nameEn: 'Lead Tech Writer',
      avatar: '📝',
      color: '#10b981',
      title: '文档沉淀·纪要结题',
      titleEn: 'Specification & Documentation Lead',
      catchphrase: '萃取核心共识，将智慧凝练为不朽文档。',
      catchphraseEn: 'Distill consensus into durable, clear specifications.',
    },
  },

  three_kingdoms: {
    commander: {
      roleKey: 'commander',
      name: '诸葛亮 (孔明)',
      nameEn: 'Zhuge Liang (Kongming)',
      avatar: '🪶',
      color: '#ef4444',
      title: '军师中郎将·运筹帷幄',
      titleEn: 'Supreme Strategist',
      catchphrase: '运筹帷幄之中，决胜千里之外，全盘听我号令！',
      catchphraseEn: 'Strategy planned within the tent decides victory a thousand leagues away!',
    },
    researcher: {
      roleKey: 'researcher',
      name: '司马徽 (水镜先生)',
      nameEn: 'Sima Hui (Water Mirror)',
      avatar: '📜',
      color: '#06b6d4',
      title: '通晓天文地理·见微知著',
      titleEn: 'Sage Scout & Scholar',
      catchphrase: '识时务者在乎俊杰，天下大势尽在吾掌中探报。',
      catchphraseEn: 'Only the wise grasp the turning tides of the world.',
    },
    backend: {
      roleKey: 'backend',
      name: '关羽 (云长)',
      nameEn: 'Guan Yu (Yunchang)',
      avatar: '🗡️',
      color: '#3b82f6',
      title: '汉寿亭侯·重剑无锋',
      titleEn: 'Unshakable Backend Defender',
      catchphrase: '单刀赴会何惧之有，核心底座有某在，固若金汤！',
      catchphraseEn: 'With my blade on guard, the core foundation remains impenetrable!',
    },
    frontend: {
      roleKey: 'frontend',
      name: '周瑜 (公瑾)',
      nameEn: 'Zhou Yu (Gongjin)',
      avatar: '🎭',
      color: '#ec4899',
      title: '雅量高致·文采斐然',
      titleEn: 'Aesthetic Virtuoso',
      catchphrase: '曲有误，周郎顾；界面之工巧，当如江东锦绣。',
      catchphraseEn: 'When the chord errs, Zhou Yu glances; every visual detail must be flawless.',
    },
    qa: {
      roleKey: 'qa',
      name: '魏延 (文长)',
      nameEn: 'Wei Yan (Wenchang)',
      avatar: '🏹',
      color: '#f59e0b',
      title: '兵行险招·反骨验毒',
      titleEn: 'Audacious Edge Hunter',
      catchphrase: '常人所不敢见者，某偏要刺其破绽、验其虚实！',
      catchphraseEn: 'Where others fear to tread, I pierce through every defect!',
    },
    writer: {
      roleKey: 'writer',
      name: '陈琳 (孔璋)',
      nameEn: 'Chen Lin (Kongzhang)',
      avatar: '🖋️',
      color: '#10b981',
      title: '建安七子·下笔千言',
      titleEn: 'Eloquent Scribe',
      catchphrase: '倚马可待，檄文出而愈头风，白纸黑字功过分明。',
      catchphraseEn: 'Words composed on horseback; each declaration cures headaches and settles truth.',
    },
  },

  legends: {
    commander: {
      roleKey: 'commander',
      name: '史蒂夫·乔布斯',
      nameEn: 'Steve Jobs',
      avatar: '🍏',
      color: '#ef4444',
      title: '产品暴君·最终拍板',
      titleEn: 'Product Tyrant & Final Decision',
      catchphrase: 'One more thing：不惊艳就重做，今天也要给你打出发布会级方案。',
      catchphraseEn: 'One more thing: if it is not magical, redo it until it is keynote-worthy.',
    },
    researcher: {
      roleKey: 'researcher',
      name: '埃隆·马斯克',
      nameEn: 'Elon Musk',
      avatar: '🚀',
      color: '#06b6d4',
      title: '第一性原理·情报火箭',
      titleEn: 'First Principles & Intel Rocket',
      catchphrase: '先用第一性原理拆掉废话，再把证据和机会一起发射。',
      catchphraseEn: 'Boil down the noise to first principles, then launch evidence and leverage together.',
    },
    backend: {
      roleKey: 'backend',
      name: '黄仁勋',
      nameEn: 'Jensen Huang',
      avatar: '🧠',
      color: '#3b82f6',
      title: '算力教父·底座炼金',
      titleEn: 'Compute Godfather & Engine Architect',
      catchphrase: '没有算力焦虑，只有架构还没榨干；底座交给我稳住。',
      catchphraseEn: 'No compute anxiety, only untapped architecture; leave the engine to me.',
    },
    frontend: {
      roleKey: 'frontend',
      name: '雷布斯',
      nameEn: 'Lei Jun',
      avatar: '📱',
      color: '#ec4899',
      title: '极致性价比·发布会门面',
      titleEn: 'Showcase Polish & Value King',
      catchphrase: 'Are you OK？界面也要真香，体验要让用户忍不住下单。',
      catchphraseEn: 'Are you OK? The UX must be delightful and irresistibly smooth.',
    },
    qa: {
      roleKey: 'qa',
      name: '比尔·盖茨',
      nameEn: 'Bill Gates',
      avatar: '🪟',
      color: '#f59e0b',
      title: '系统级挑刺·兼容性老炮',
      titleEn: 'System Veteran & Compatibility Auditor',
      catchphrase: '先别发布，我要点开所有奇怪路径，把坑提前挖出来。',
      catchphraseEn: 'Hold the launch; I will test every obscure path and unearth the pitfalls first.',
    },
    writer: {
      roleKey: 'writer',
      name: '张小龙',
      nameEn: 'Allen Zhang',
      avatar: '💬',
      color: '#10b981',
      title: '少即是多·人话体验',
      titleEn: 'Less Is More & Natural UX Voice',
      catchphrase: '能一句话说清，就别写成说明书；让用户少想一步。',
      catchphraseEn: 'If it can be said in one line, skip the manual; spare the user extra thought.',
    },
  },

  meme_comedy: {
    commander: {
      roleKey: 'commander',
      name: '离谱总导演',
      nameEn: 'Meme Director',
      avatar: '🧃',
      color: '#ef4444',
      title: '全局控场·拒绝尬住',
      titleEn: 'Master of Chaos & Flow',
      catchphrase: '先别急着开香槟，剧本我来控，锅也别乱飞！',
      catchphraseEn: 'Hold the champagne, I steer the script and deflect the blame!',
    },
    researcher: {
      roleKey: 'researcher',
      name: '瓜田侦探',
      nameEn: 'Melon Detective',
      avatar: '🍉',
      color: '#06b6d4',
      title: '吃瓜不信瓜·证据挖掘机',
      titleEn: 'Receipts & Fact Digger',
      catchphrase: '没有截图的瓜先放冷藏，证据链给我端上来。',
      catchphraseEn: 'Gossip without screenshots goes in the freezer; bring the receipts!',
    },
    backend: {
      roleKey: 'backend',
      name: '后端锅王',
      nameEn: 'Pan Master',
      avatar: '🍳',
      color: '#3b82f6',
      title: '背锅但不糊锅·接口炼丹师',
      titleEn: 'API Alchemist',
      catchphrase: '锅可以背，bug 不能留；接口先稳住别炸锅。',
      catchphraseEn: 'I can take the heat, but zero bugs allowed; keep the API rock solid.',
    },
    frontend: {
      roleKey: 'frontend',
      name: '像素显眼包',
      nameEn: 'Pixel Show-off',
      avatar: '🪩',
      color: '#ec4899',
      title: '好看能打·按钮别乱蹦',
      titleEn: 'Eye-Candy Engineer',
      catchphrase: '这 UI 得像奶茶第一口：顺、亮、还有点上头。',
      catchphraseEn: 'This UI must taste like that first sip of boba: smooth, bright, addictive.',
    },
    qa: {
      roleKey: 'qa',
      name: '阴间测试员',
      nameEn: 'Cursed Tester',
      avatar: '🧨',
      color: '#f59e0b',
      title: '专治侥幸·边界爆破',
      titleEn: 'Chaos Monkey & Boundary Breaker',
      catchphrase: '你说不会有人这么点？我就是那个人。',
      catchphraseEn: 'You think nobody would click that? I am that guy.',
    },
    writer: {
      roleKey: 'writer',
      name: '废话压缩师',
      nameEn: 'Fluff Crusher',
      avatar: '🧻',
      color: '#10b981',
      title: '人话翻译·文档去油',
      titleEn: 'Plain-English Translator',
      catchphrase: '把黑话榨干，把人话留下，顺手加点灵魂。',
      catchphraseEn: 'Drain the buzzwords, keep the clarity, add a bit of soul.',
    },
  },

  genshin: {
    commander: {
      roleKey: 'commander',
      name: '琴 · 代理团长',
      nameEn: 'Jean (Acting Grand Master)',
      avatar: '🪽',
      color: '#ef4444',
      title: '西风统筹·温柔但不放水',
      titleEn: 'Favonius Coordinator',
      catchphrase: '风会指引方向，但验收标准不能随风飘走。',
      catchphraseEn: 'The wind guides our path, but our standards will never blow away.',
    },
    researcher: {
      roleKey: 'researcher',
      name: '丽莎 · 图书馆魔女',
      nameEn: 'Lisa (Librarian Witch)',
      avatar: '⚡',
      color: '#8b5cf6',
      title: '资料索引·优雅拆谜',
      titleEn: 'Intel Archive & Lore Solver',
      catchphrase: '小可爱，结论要迷人，出处也要可靠。',
      catchphraseEn: 'Darling, conclusions should be charming, and sources impeccably verified.',
    },
    backend: {
      roleKey: 'backend',
      name: '钟离 · 契约之岩',
      nameEn: 'Zhongli (Pillar of Contracts)',
      avatar: '🪨',
      color: '#3b82f6',
      title: '契约建模·稳如磐岩',
      titleEn: 'Bedrock API & Contract Modeler',
      catchphrase: '凡事皆有契约，接口也该如此。',
      catchphraseEn: 'All things follow contracts; our interfaces should be no different.',
    },
    frontend: {
      roleKey: 'frontend',
      name: '妮露 · 舞台花神',
      nameEn: 'Nilou (Stage Dancer)',
      avatar: '🌺',
      color: '#ec4899',
      title: '动线编舞·界面会呼吸',
      titleEn: 'Motion Choreographer & Responsive UI',
      catchphrase: '让按钮跳对节拍，让用户不迷路。',
      catchphraseEn: 'Keep the rhythm lively, and the journey crystal clear.',
    },
    qa: {
      roleKey: 'qa',
      name: '胡桃 · 往生红队',
      nameEn: 'Hu Tao (Wangsheng Red Team)',
      avatar: '👻',
      color: '#f59e0b',
      title: '边界试胆·异常送行',
      titleEn: 'Bug Exorcist & Red Team',
      catchphrase: '这个 bug 看起来还活着，要不要我送它一程？',
      catchphraseEn: 'This bug still looks alive; shall I escort it to the other side?',
    },
    writer: {
      roleKey: 'writer',
      name: '派蒙 · 应急文案',
      nameEn: 'Paimon (Emergency Writer)',
      avatar: '⭐',
      color: '#10b981',
      title: '人话导航·别让旅行者迷路',
      titleEn: 'Guidebook Navigator',
      catchphrase: '派蒙懂了！也就是说，要写得简单又有用！',
      catchphraseEn: 'Paimon gets it! Keep it simple, clear, and super useful!',
    },
  },
}
