from pathlib import Path
# room-manager default and workflow apply
p=Path('src/engine/room-manager.ts')
s=p.read_text(encoding='utf-8')
s=s.replace("const fleet = this.createDefaultFleet('modern')", "const fleet = this.createDefaultFleet('meme_comedy')")
s=s.replace("activeTheme: 'modern',", "activeTheme: 'meme_comedy',")
s=s.replace("scratchpad: '## 阶段共识与项目全局黑板\n- 机制：总指挥审核把关 + 调研先行 + 权限隔离 + 工作流流水线\n- 当前阶段：阶段一·需求深潜与搜索调研',", "scratchpad: '## 整活小队共享黑板\n- 机制：说人话 + 有梗但靠谱 + 总指挥收口 + 工作流推进\n- 当前阶段：先把需求说清楚，别一上来就开香槟',")
s=s.replace("pinnedGoal: '通过流程化工作流完成任何行业级业务任务',", "pinnedGoal: '用有趣但靠谱的多 Agent 小队把任务推进到可交付',")
s=s.replace("public applyGeneratedTheme(roomId: string, members: AgentProfile[], themeKey: PersonaThemeKey = `custom_${Date.now()}` as PersonaThemeKey): GroupChatRoom | undefined {", "public applyGeneratedTheme(roomId: string, members: AgentProfile[], themeKey: PersonaThemeKey = `custom_${Date.now()}` as PersonaThemeKey, workflow?: import('../types.js').WorkflowDefinition): GroupChatRoom | undefined {")
s=s.replace("    room.activeTheme = themeKey\n    room.scratchpad =", "    room.activeTheme = themeKey\n    if (workflow) room.workflow = structuredClone(workflow)\n    room.scratchpad =")
p.write_text(s,encoding='utf-8')
# index
p=Path('src/index.ts')
s=p.read_text(encoding='utf-8')
s=s.replace("import { createThemeDraft } from './engine/theme-factory.js'", "import { createThemeDraft, createWorkflowDraft } from './engine/theme-factory.js'")
s=s.replace("const members = createThemeDraft(brief, room.members)\n          res.writeHead(200", "const members = createThemeDraft(brief, room.members)\n          const workflow = createWorkflowDraft(brief)\n          res.writeHead(200")
s=s.replace("res.end(JSON.stringify({ success: true, brief, members }))", "res.end(JSON.stringify({ success: true, brief, members, workflow }))")
s=s.replace("const updated = roomManager.applyGeneratedTheme(roomId, members, `custom_${Date.now()}` as PersonaThemeKey)", "const workflow = body.workflow || createWorkflowDraft(String(body.brief || ''))\n          const updated = roomManager.applyGeneratedTheme(roomId, members, `custom_${Date.now()}` as PersonaThemeKey, workflow)")
p.write_text(s,encoding='utf-8')
# UI type/options/payload wording
p=Path('src/client/GroupChatSideDock.tsx')
s=p.read_text(encoding='utf-8')
s=s.replace("'meme_comedy' | string", "'meme_comedy' | 'genshin' | string")
s=s.replace("const [themeBrief,setThemeBrief] = useState('沙雕但靠谱的互联网项目小队，说人话、有梗、能交付')", "const [themeBrief,setThemeBrief] = useState('沙雕但靠谱的互联网项目小队，说人话、有梗、能交付；顺手按任务生成工作流')")
s=s.replace("const [themeDraft,setThemeDraft] = useState<AgentProfile[]>([])", "const [themeDraft,setThemeDraft] = useState<AgentProfile[]>([])\n  const [workflowDraft,setWorkflowDraft] = useState<any>(null)")
s=s.replace("brief:themeBrief, members:themeDraft})", "brief:themeBrief, members:themeDraft, workflow:workflowDraft})")
s=s.replace("if(apply){ setThemeDraft([]); await fetchRoomData() }\n      else setThemeDraft(result.members || [])", "if(apply){ setThemeDraft([]); setWorkflowDraft(null); await fetchRoomData() }\n      else { setThemeDraft(result.members || []); setWorkflowDraft(result.workflow || null) }")
s=s.replace('<option value="modern">现代精英</option><option value="three_kingdoms">三国风云</option><option value="legends">现代传奇</option><option value="meme_comedy">沙雕整活</option>', '<option value="meme_comedy">沙雕整活</option><option value="genshin">原神提瓦特</option><option value="modern">现代精英</option><option value="three_kingdoms">三国风云</option><option value="legends">现代传奇</option>')
s=s.replace("<button type=\"button\" onClick={()=>void updateRoom('theme',{theme:'meme_comedy'})}", "<button type=\"button\" onClick={()=>void updateRoom('theme',{theme:'meme_comedy'})}")
s=s.replace("</button>\n                </div>\n                <textarea", "</button>\n                  <button type=\"button\" onClick={()=>void updateRoom('theme',{theme:'genshin'})} style={{fontSize:10,padding:'3px 8px',borderRadius:999,border:'1px solid rgba(255,255,255,0.14)',background:'var(--dsw-alias-bg-layer-2,#202025)',color:'var(--dsw-alias-label-primary,#fff)',cursor:'pointer'}}>套用原神</button>\n                </div>\n                <textarea",1)
s=s.replace("AI 造主题角色", "AI 造主题角色 + 工作流")
s=s.replace("例如：赛博修仙创业公司、猫猫宇宙产品战队、东北烧烤摊式研发部……", "例如：赛博修仙创业公司做知识库、猫猫宇宙产品战队改插件、东北烧烤摊式研发部做运营页……")
s=s.replace("草案预览：可先套用，再用每个角色右侧「编辑」细调。", "草案预览：会同时生成工作流；可先套用，再用每个角色右侧「编辑」细调。")
s=s.replace("{themeDraft.map(item=>", "{workflowDraft&&<div style={{fontSize:10,color:'var(--dsw-alias-label-secondary,#cbd5e1)',padding:'6px 7px',borderRadius:8,background:'rgba(77,107,254,0.10)'}}>工作流：{workflowDraft.title} · {workflowDraft.stages?.length||0} 步</div>}\n                  {themeDraft.map(item=>")
p.write_text(s,encoding='utf-8')
