const { spawnSync } = require('node:child_process')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const steps = [
  ['npm', ['run', 'typecheck']],
  ['node', ['__tests__/test-tool-routing.cjs']],
  ['node', ['__tests__/test-auto-setup.cjs']],
  ['node', ['__tests__/test-default-options.cjs']],
  ['node', ['__tests__/test-orchestrator-policy.cjs']],
  ['node', ['__tests__/test-p1-assignment-mailbox.cjs']],
  ['node', ['__tests__/test-p2-workflow-task-dag.cjs']],
  ['node', ['__tests__/test-p3-model-recommender.cjs']],
  ['node', ['__tests__/test-p4-dsh-compat.cjs']],
  ['node', ['__tests__/test-p5-hud.cjs']],
  ['node', ['__tests__/test-p6-structured-result.cjs']],
  ['node', ['__tests__/test-p7-hud-actions.cjs']],
  ['node', ['__tests__/test-p8-overlay-layout.cjs']],
  ['node', ['__tests__/test-p9-draggable-hud.cjs']],
  ['node', ['__tests__/test-p10-e2e-definition.cjs']],
  ['node', ['__tests__/test-p11-preflight-definition.cjs']],
  ['node', ['__tests__/test-p12-official-chat-compat.cjs']],
  ['node', ['__tests__/test-p13-hud-chat-entry.cjs']],
  ['node', ['__tests__/test-p14-safe-middle-conversation-tab.cjs']],
  ['node', ['__tests__/test-p15-auto-plan-confirm-flow.cjs']],
  ['node', ['__tests__/test-p16-theme-voice-copy-system.cjs']],
  ['node', ['__tests__/test-p17-hud-director-console.cjs']],
  ['node', ['__tests__/test-p18-browser-visual-regression.cjs']],
  ['npm', ['run', 'build:all']],
  ['node', ['__tests__/test-p19-real-project-loop.cjs']],
  ['node', ['__tests__/test-p20-low-friction-onboarding.cjs']],
  ['node', ['__tests__/test-p21-hud-top-controls-component.cjs']],
  ['node', ['__tests__/test-p22-hud-workflow-panel-component.cjs']],
  ['node', ['__tests__/test-p23-hud-roster-panel-component.cjs']],
  ['node', ['__tests__/test-p24-hud-scratchpad-panel-component.cjs']],
  ['node', ['__tests__/test-p25-sidedock-type-dedupe.cjs']],
  ['node', ['__tests__/test-p26-hud-shared-types.cjs']],
  ['node', ['__tests__/test-p27-hud-style-tokens.cjs']],
  ['node', ['__tests__/test-p28-roster-style-tokens.cjs']],
  ['node', ['__tests__/test-p29-workflow-style-tokens.cjs']],
  ['node', ['__tests__/test-p30-top-controls-style-tokens.cjs']],
  ['node', ['__tests__/test-p31-final-usability-acceptance.cjs']],
  ['node', ['__tests__/test-p32-workflow-progressive-disclosure.cjs']],
  ['node', ['__tests__/test-p33-workflow-compact-browser-check.cjs']],
  ['node', ['__tests__/test-p34-workflow-accordion-details.cjs']],
  ['node', ['__tests__/test-p35-team-ledger-tab-split.cjs']],
  ['node', ['__tests__/test-p36-ledger-progressive-records.cjs']],
  ['node', ['__tests__/test-p37-team-progressive-roster.cjs']],
  ['node', ['__tests__/test-p38-official-source-dialog-guard.cjs']],
  ['node', ['__tests__/test-p39-source-agent-tab-switch-regression.cjs']],
  ['node', ['__tests__/test-p40-refresh-state-cleanup-regression.cjs']],
  ['node', ['__tests__/test-p42-agent-chat-entry-usable-regression.cjs']],
  ['node', ['__tests__/test-p43-final-closure-audit.cjs']],
  ['node', ['__tests__/test-p44-source-dialog-prepare-diagnostic.cjs']],
  ['node', ['__tests__/test-p45-theme-aware-central-copy.cjs']],
  ['node', ['__tests__/test-p46-i18n-panel-task-smoke.cjs']],
  ['node', ['__tests__/test-p47-bilingual-ui-and-tool-scope.cjs']],
  ['node', ['__tests__/test-p48-real-agent-loop-quality.cjs']],
  ['node', ['__tests__/test-p49-agent-timeout-diagnostic.cjs']],
  ['node', ['__tests__/test-p50-real-moderator-led-loop.cjs']],
  ['node', ['__tests__/test-p51-task-tier-progress.cjs']],
  ['node', ['__tests__/test-p52-autosetup-dispatch-guard.cjs']],
  ['node', ['__tests__/test-p53-message-ledger-persistence.cjs']],
  ['node', ['__tests__/test-p54-interrupted-assignment-recovery.cjs']],
  ['node', ['__tests__/test-p55-bilingual-export-summary.cjs']],
  ['node', ['__tests__/test-p56-runtime-autosetup-i18n.cjs']],
  ['node', ['__tests__/test-p57-agent-runtime-prompt-i18n.cjs']],
  ['node', ['__tests__/test-p58-tool-workflow-api-i18n.cjs']],
  ['node', ['__tests__/test-p59-theme-workflow-content-i18n.cjs']],
  ['node', ['__tests__/test-p60-tech-legends-theme.cjs']],
  ['node', ['__tests__/test-p61-english-source-bilingual-runtime.cjs']],
  ['node', ['__tests__/test-p62-runtime-agent-watchdog.cjs']],
  ['node', ['__tests__/test-p63-assignment-watchdog-timeout.cjs']],
  ['node', ['__tests__/test-p64-chat-ui-composer-progression.cjs']],
  ['node', ['__tests__/test-p65-captain-task-protocol.cjs']],
  ['node', ['__tests__/test-p66-durable-subagent-resume.cjs']],
  ['node', ['__tests__/test-p67-approve-run-transaction-card.cjs']],
  ['node', ['__tests__/test-p68-team-coordination-tools.cjs']],
  ['node', ['__tests__/test-p69-task-cockpit-productization.cjs']],
  ['node', ['__tests__/test-p70-model-health-and-switching.cjs']],
  ['node', ['__tests__/test-p71-new-session-agent-entry.cjs']],
  ['node', ['__tests__/test-p72-hud-message-margins.cjs']],
  ['node', ['__tests__/test-p73-hero-left-collapse.cjs']],
  ['node', ['__tests__/test-p74-session-room-binding.cjs']],
  ['node', ['__tests__/test-p75-distinct-theme-copy.cjs']],
  ['node', ['__tests__/test-p76-hud-locale-toggle-header.cjs']],
  ['node', ['__tests__/test-p77-central-live-execution-status.cjs']],
  ['node', ['__tests__/test-p78-agent-turn-surface-fallback.cjs']],
  ['node', ['__tests__/test-p79-composer-outside-scroll.cjs']],
  ['node', ['__tests__/test-p80-central-loading-state.cjs']],
  ['node', ['__tests__/test-p81-workflow-commander-delegation.cjs']],
  ['node', ['__tests__/test-p82-official-like-central-execution.cjs']],
  ['node', ['__tests__/test-p83-hero-entry-self-click-guard.cjs']],
  ['node', ['__tests__/test-p84-collapsible-message-body.cjs']],
  ['node', ['__tests__/test-p85-bilingual-role-coverage.cjs']],
  ['node', ['__tests__/test-p86-native-tool-row-adapter.cjs']],
  ['node', ['__tests__/test-p87-dialog-continuity.cjs']],
  ['node', ['__tests__/test-p88-official-tools-and-cache-metrics.cjs']],
  ['node', ['__tests__/test-p89-dsh-native-foundation.cjs']],
  ['node', ['__tests__/test-long-dialog-e2e.cjs']],
  ['node', ['scripts/e2e-no-llm.cjs']],
  ['npm', ['run', 'preflight']],
]

for (const [cmd, args] of steps) {
  console.log(`\n[MATRIX] ${cmd} ${args.join(' ')}`)
  const result = spawnSync(cmd, args, { cwd: root, stdio: 'inherit', shell: process.platform === 'win32' })
  if (result.status !== 0) {
    console.error(`[MATRIX] failed: ${cmd} ${args.join(' ')} -> ${result.status}`)
    process.exit(result.status || 1)
  }
}
console.log('\nTEST_MATRIX_EXIT:0')


